print('Hello world!')
print("So many times 'Hello world!', hope will get what I want this time")
print("I created a backup repository on Github" + " Let's test whether we can push a modification simultaneously")
print("Failed, try again")
print("Why the default repository is that of Gitee rather than Github?")